use_frameworks!

target 'Example' do
    pod 'ESPullToRefresh', '~> 2.6'
    pod 'NVActivityIndicatorView', '~> 3.7'
    pod 'Floaty', '~> 3'
    pod 'Grouper', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.1'
        end
    end
end
